"""add_ml_fields_to_transactions

Revision ID: 11a98d342b85
Revises: 001_initial
Create Date: 2026-06-24 13:11:23.633220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '11a98d342b85'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('fraud_probability', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'model_version')
    op.drop_column('transactions', 'fraud_probability')
    # ### end Alembic commands ###
